# Generated by Django 4.2.18 on 2025-01-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Salary', models.IntegerField()),
                ('Score', models.FloatField()),
                ('EmpJoiningDate', models.DateField()),
                ('is_employee', models.BooleanField()),
            ],
        ),
    ]
